version: '3.8'

services:
 spark-master:
  image: bitnami/spark:latest
  command: bin/spark-class org.apache.spark.deploy.master.Master
  hostname: master
  container_name: spark-master
  ports:
  - "9090:8080"
  - "7077:7077"
 spark-worker-1:
  image: bitnami/spark:latest
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  container_name: spark-worker-1
  depends_on:
  - spark-master
  environment:
   SPARK_MODE: worker
   SPARK_WORKER_CORES: 2
   SPARK_WORKER_MEMORY: 2g
   SPARK_MASTER_URL: spark://spark-master:7077
 spark-worker-2:
  image: bitnami/spark:latest
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  container_name: spark-worker-2
  depends_on:
  - spark-master
  environment:
   SPARK_MODE: worker
   SPARK_WORKER_CORES: 2
   SPARK_WORKER_MEMORY: 2g
   SPARK_MASTER_URL: spark://spark-master:7077
  # environment:
  #  - SPARK_LOCAL_IP=127.0.0.1
  #  - SPARK_LOCAL_HOSTNAME=localhost
  #  - SPARK_IDENT_STRING=localhost
  #  - SPARK_PUBLIC_DNS=127.0.0.1
  #   - SPARK_CONF_DIR=/conf
  #   - SPARK_DIVER_CORES=1
  #   - SPARK_DRIVER_MEMORY=1g
  #   - SPARK_MASTER_ENDPOINT=spark-master
  #   - SPARK_MASTER_PORT=7077
  #   - LIVY_FILE_LOCAL_DIR_WHITELIST=/opt/jars
 # spark-livy:
 #  image: panovvv/livy:latest
 #  command: ["sh", "-c", "/opt/bitnami/livy/bin/livy-server"]
 #  user: root
 #  container_name: spark-livy
 #  # environment:
 #  #  - SPARK_LOCAL_IP=127.0.0.1
 #  #  - SPARK_LOCAL_HOSTNAME=localhost
 #  #  - SPARK_IDENT_STRING=localhost
 #  #  - SPARK_PUBLIC_DNS=127.0.0.1
 #  #   - SPARK_CONF_DIR=/conf
 #  #   - SPARK_DIVER_CORES=1
 #  #   - SPARK_DRIVER_MEMORY=1g
 #  #   - SPARK_MASTER_ENDPOINT=spark-master
 #  #   - SPARK_MASTER_PORT=7077
 #  #   - LIVY_FILE_LOCAL_DIR_WHITELIST=/opt/jars
 #  # volumes:
 #  #   - type: bind
 #  #     source: ./livy-server/conf/
 #  #     target: /opt/bitnami/livy/conf/
 #  #   - type: bind
 #  #     source: ./livy-server/target/
 #  #     target: /target/
 #  #   - type: bind
 #  #     source: ./livy-server/data/
 #  #     target: /data/
 #  ports:
 #    - '8998:8998'
 #  depends_on:
 #    - "spark-master"
 #    - "spark-worker-1"
 #    - "spark-worker-2"
 spark-livy:
    image: panovvv/livy:latest
#    build: '../livy-docker'
    hostname: livy
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    volumes:
      - ./livy_batches:/livy_batches
      - ./data:/data
    environment:
      - SPARK_MASTER=yarn
      # Intentionally not specified - if it's set here, then we can't override it
      # via REST API ("conf"={} map)
      # Can be client or cluster
#      - SPARK_DEPLOY_MODE=client

      - LOCAL_DIR_WHITELIST=/data/batches/
      - ENABLE_HIVE_CONTEXT=false
      # Defaults are fine for variables below. Uncomment to change them.
#      - LIVY_HOST=0.0.0.0
#      - LIVY_PORT=8998
    expose:
      - 1-65535
    ports:
      - 8998:8998
    # networks:
    #   spark_net:
    #     ipv4_address: 172.28.1.6
    # extra_hosts:
    #   - "master:172.28.1.1"
    #   - "worker1:172.28.1.2"
    #   - "worker2:172.28.1.3"
    #   - "hivemetastore:172.28.1.4"
    #   - "zeppelin:172.28.1.5"
 jupyter:
  image: mikev/sparkmagic:draft1
  container_name: jupyter
  volumes:
  - "./jupyter-data:/home/mvier"
  ports:
  - 8888:8888
  depends_on:
    - "spark-livy"